# Generated by Django 5.0.4 on 2024-04-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
    ]
