# Generated by Django 5.0.4 on 2024-04-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitexpense',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.expensetypes'),
        ),
    ]
