# Generated by Django 5.0.4 on 2024-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_splitexpense_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitexpense',
            name='user',
        ),
        migrations.AddField(
            model_name='splitexpense',
            name='user',
            field=models.ManyToManyField(to='expense.user'),
        ),
    ]
