# Generated by Django 5.0.4 on 2024-04-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_remove_splitexpense_user_splitexpense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitexpense',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='splitexpense',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='splitexpense',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='SplitExpense',
        ),
    ]
