# Generated by Django 5.0.4 on 2024-04-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_remove_splitexpense_expense_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseTypes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
